import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use - ToolMate",
  description: "Terms of Use for ToolMate - Read our terms and conditions for using our free online tools.",
};

export default function TermsOfUsePage() {
  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <div>
        <h1 className="text-4xl font-bold tracking-tight">Terms of Use</h1>
        <p className="mt-2 text-slate-600">Last updated: November 28, 2024</p>
      </div>

      <div className="prose prose-slate max-w-none space-y-6">
        <section>
          <h2 className="text-2xl font-semibold">Agreement to Terms</h2>
          <p className="text-slate-600">
            By accessing and using ToolMate, you accept and agree to be bound by the terms and provisions 
            of this agreement. If you do not agree to these terms, please do not use our services.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Use License</h2>
          <p className="text-slate-600">
            Permission is granted to use our tools for personal and commercial purposes. This license includes:
          </p>
          <ul className="list-disc pl-6 text-slate-600 space-y-2">
            <li>Free access to all available tools</li>
            <li>Unlimited usage of our services</li>
            <li>No registration required</li>
          </ul>
          <p className="text-slate-600 mt-4">
            You may not:
          </p>
          <ul className="list-disc pl-6 text-slate-600 space-y-2">
            <li>Attempt to reverse engineer or copy our tools</li>
            <li>Use our services for illegal activities</li>
            <li>Overload our servers with automated requests</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Disclaimer</h2>
          <p className="text-slate-600">
            The tools and services are provided &quot;as is&quot; without any warranties. We do not guarantee:
          </p>
          <ul className="list-disc pl-6 text-slate-600 space-y-2">
            <li>Uninterrupted or error-free operation</li>
            <li>Accuracy of results generated by our tools</li>
            <li>Fitness for a particular purpose</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Limitations of Liability</h2>
          <p className="text-slate-600">
            ToolMate shall not be liable for any damages arising from the use or inability to use our services, 
            including but not limited to direct, indirect, incidental, or consequential damages.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Changes to Terms</h2>
          <p className="text-slate-600">
            We reserve the right to modify these terms at any time. Continued use of the service after 
            changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Contact Information</h2>
          <p className="text-slate-600">
            For questions about these Terms of Use, please visit our{" "}
            <a href="/contact" className="text-blue-600 hover:underline">
              Contact Page
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
